from flask import Flask, render_template
from models import Estado
from models import Noticia
app = Flask(__name__)

acre = Estado(0, 'Acre', 'AC', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Acre-300x210.png')
alagoas = Estado(1, 'Alagoas', 'AL', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Alagoas-300x200.png')
amapa = Estado(2, 'Amapá', 'AP', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Amapa-300x210.png' )
amazonas = Estado(3, 'Amazonas', 'AM', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Amazonas-300x214.png' )
bahia = Estado(4, 'Bahia', 'BA', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_da_Bahia-300x200.png')
ceara = Estado(5, 'Ceará', 'CE', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Ceara-300x210.png')
distritoFederal = Estado(6, 'Distrito Federal', 'DF', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Distrito_Federal_Brasil-300x210.png')
espiritoSanto = Estado(7, 'Espírito Santo', 'ES', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Espirito_Santo-300x210.png')
goias = Estado(8, 'Goiás', 'GO', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Goias-300x210.png')
maranhao = Estado(9, 'Maranhão', 'MA', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Maranhao-300x200.png')
matoGrosso = Estado(10, 'Mato Grosso', 'MT', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Mato_Grosso-300x210.png')
matoGrossoSul = Estado(11, 'Mato Grosso do Sul', 'MS', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Mato_Grosso_do_Sul-300x210.png')
minasGerais = Estado(12, 'Minas Gerais', 'MG','https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Minas_Gerais-300x210.png')
para = Estado(13, 'Pará', 'PA', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Para-300x200.png')
paraiba = Estado(14, 'Paraíba', 'PB', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_da_Paraiba-300x210.png')
parana = Estado(15, 'Paraná', 'PR', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Parana-300x210.png')
pernambuco = Estado(16, 'Pernambuco', 'PE', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Pernambuco-300x210.png')
piaui = Estado(17, 'Piauí', 'PI', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Piaui-300x200.png')
rioJaneiro = Estado(18, 'Rio de Janeiro', 'RJ', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_Rio_de_Janeiro-300x210.png')
rioGrandeNorte = Estado(19, 'Rio Grande do Norte', 'RN', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Rio_Grande_do_Norte-300x200.png')
rioGrandeSul = Estado(20, 'Rio Grande do Sul', 'RS', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Rio_Grande_do_Sul-300x210.png')
rondonia = Estado(21, 'Rondônia', 'RO', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Rondonia-300x210.png')
roraima = Estado(22, 'Roraima', 'RR', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Roraima-300x200.png')
santaCatarina = Estado(23, 'Santa Catarina', 'SC', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Santa_Catarina-300x218.png')
saoPaulo = Estado(24, 'São Paulo', 'SP', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_Sao_Paulo-300x200.png')
sergipe = Estado(25, 'Sergipe', 'SE', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_de_Sergipe-300x210.png')
tocantis = Estado(26, 'Tocantins', 'TO', 'https://mundodageografia.com.br/wp-content/uploads/2020/10/Bandeira_do_Tocantins-300x210.png')

noticia_acre = [Noticia(0, "Equipes de saúde de Rio Branco aplicam vacina contra a Covid-19 em postos de saúde nesta quarta (30)", "Equipes atendem população com as 4ª doses da vacina contra a Covid. Atendimento é feito das 8h às 16h.", "../static/img/noticia1acre.jpeg", "As equipes de saúde de Rio Branco continuam com a imunização contra a Covid-19 nesta quarta-feira (30). Nos pontos de vacinação são aplicadas a 1ª, 2ª e dose de reforço no público adulto e infantil e a 4ª dose, exclusivamente, em idosos acima dos 80 anos. O atendimento é feito das 8h às 16h. A 1ª e 2ª dose são disponibilizadas para pessoas com mais de 12 anos. Já a dose de reforço é aplicada em adultos acima dos 18 anos que tenham completado 4 meses desde a última dose e pessoas com baixa imunidade (imunossuprimidos). Quem tomou a primeira dose da Janssen há 2 meses ou mais deve comparece à Urap Vila Ivonete e tomar a dose de reforço. É necessário apresentar a carteirinha de vacinação comprovando que tomou a 1ª dose da Janssen há mais de 60 dias.", "29/03/2022", "Latest news", acre, 7330, 550)]
noticia_alagoas = [Noticia(1, "Boletim Covid-19 (30/03)", "Alagoas tem 296.145 casos e 6.880 óbitos", "../static/img/noticia1alagoas.png", "O Boletim Epidemiológico da Secretaria de Estado da Saúde (Sesau), desta quarta-feira (30), apresenta 79 casos de Covid-19 em Alagoas. Dessa forma, o Estado tem um total de 296.145 casos confirmados do novo coronavírus até o momento, dos quais 256 estão em isolamento domiciliar. Outros 288.787 pacientes já finalizaram o período de isolamento, não apresentam mais sintomas e, portanto, estão recuperados da doença. Há 1.623 casos em investigação epidemiológica. Foram registrados quatro óbitos em território alagoano. Com isso, Alagoas tem 6.880 óbitos por Covid-19. Os casos confirmados de pessoas com a Covid-19 estão distribuídos nos 102 municípios alagoanos. Em relação ao quadro total de óbitos em Alagoas, estão confirmados 6.880 óbitos por Covid-19, mas, oito deles, eram de pessoas residentes em Pernambuco, São Paulo, Santa Catarina e Bahia, tendo como vítimas seis homens e duas mulheres. Dos 6.872 óbitos de pessoas residentes em Alagoas, 3.785 eram do sexo masculino e 3.087 do sexo feminino. Eram 3.054 pessoas que residiam em Maceió e as outras 3.818 moravam no interior do Estado, segundo o Centro de Informações Estratégicas de Vigilância em Saúde (Cievs), da Sesau.", "30/03/2022", "Latest news", alagoas, 11200, 450)]
noticia_amapa = [Noticia(2, "Boletim Covid-19 (27/03)", "Amapá tem 160.328 casos confirmados, 2 amostras em análise laboratorial, 129.497 pessoas recuperadas e 2.122 óbitos. A taxa de imunização da população vacinável é 69% para a primeira dose da vacina.", "../static/img/noticia1amapa.jpg", "O Governo do Amapá atualiza, neste domingo, 27, o boletim informativo sobre a situação do novo coronavírus no estado. Agora, são 160.328 casos confirmados, 2 amostras em análise laboratorial e 1.047.751 doses de vacinas aplicadas em todos os 16 municípios do estado. Os testes também descartaram 161.801 casos suspeitos.", "27/03/2022", "Latest news", amapa, 2000, 220)]
noticia_amazonas = [Noticia(3, "Amazonas tem 67 novos casos e uma morte por Covid-19", "O total de vidas perdidas para a doença chega a 14.153 desde o início da pandemia.", "../static/img/noticia1amazonas.jpg", "O Amazonas registrou mais 67 novos casos de Covid-19 nas últimas 24 horas, segundo dados do boletim da Fundação de Vigilância em Saúde do Amazonas (FVS-AM) divulgados nesta terça-feira (29). Desde o início da pandemia, o número de pessoas que contraíram a doença no estado chega a 581.177 infectados. Dos 581.177 casos confirmados no Amazonas até esta terça-feira (29/03), 290.265 são de Manaus (49,94%) e 290.912 do interior do estado (50,06%). A capital, Manaus, tem 28 novos casos confirmados. Foi registrado 1 óbito pela Covid-19, que ocorreu em Coari, em uma data anterior, porém foi confirmado nesta terça-feira depois de exames. O total de vidas perdidas para a doença chega a 14.153 desde o início da pandemia. Entre as vítimas em Manaus, há o registro de 9.694 óbitos confirmados em decorrência do novo coronavírus. No interior, são 61 municípios com óbitos confirmados até o momento, totalizando 4.459.", "29/03/2022", "Latest news", amazonas, 2300, 410)]
noticia_bahia = [Noticia(4, "Bahia tem 877 novos casos conhecidos de Covid-19 em 24h", "Estado contabiliza 1.299 casos ativos da doença nesta quarta (30).", "../static/img/noticia1bahia.jpg", "A Bahia tem 1.299 casos ativos de Covid-19, segundo dados divulgados nesta quarta-feira (30), pela Secretaria Estadual da Saúde (Sesab). Além disso, nas últimas 24 horas, foram registrados 877 casos conhecidos da doença e 12 óbitos. Desde o início da pandemia, 1.531.824 casos foram confirmados, 1.500.825 são considerados recuperados e 29.700 pessoas morreram.", "30/03/2022", "Latest news", bahia, 38230, 8240)]
noticia_ceara = [Noticia(5, "Mais de 80 mil idosos estão aptos a receber a 4ª dose da vacina contra a Covid no Ceará", "Secretaria da Saúde autoriza a aplicação onde há estoque de imunizantes, mas as cidades cearenses precisam agendar o público para a segunda dose de reforço", "../static/img/noticia1ceara.jpeg", "O processo de imunização contra a Covid ganhou uma nova etapa e, pelo menos, 80.341 idosos com 80 anos ou mais podem receber a 4ª dose da vacina, também chamada de segunda dose de reforço, no Ceará. Esse grupo recebeu três doses da proteção há quatro meses ou mais. Parte do público mais vulnerável ainda precisa aguardar o intervalo estipulado. O grupo apto a receber a nova aplicação do imunizante corresponde a 41% de todas as pessoas nessa faixa etária vivendo no Ceará, que tem 195.691 idosos acima de 80 anos, conforme estimativa populacional de 2021. Os dados são da Secretaria da Saúde do Ceará (Sesa). É possível perceber pelos números que mais da metade dessa população ainda precisa aguardar o intervalo de quatro meses para receber a segunda dose de reforço. Esse cronograma depende do envio das doses pelo Ministério da Saúde.", "30/03/2022", "Latest news", ceara, 8052, 1823)]
noticia_distrito_federal = [Noticia(6, "Covid-19: Ibaneis anuncia mais imunizantes e segundo reforço para idosos", "Com a chegada de quase 48 mil doses de imunizante, que deve ocorrer nesta quinta-feira (31/3), o governador afirmou, no Twitter, que a vacinação para idosos com mais de 80 anos começa em 1º de abril", "../static/img/noticia1distritofederal.jpg", "O Governador do Distrito Federal Ibaneis Rocha (MDB) anunciou que o GDF vai receber 47.970 doses de vacina contra covid-19, da Pfizer-BioNTech, nesta quinta-feira (31/3). “Com essa remessa, iniciaremos a vacinação de idosos +80 a partir de 1º de abril. Vamos vacinar!”, disse o chefe do Executivo por meio de uma rede social. Após o Ministério da Saúde recomendar a aplicação da segunda dose de reforço para idosos acima de 80 anos, a Secretaria de Saúde do Distrito Federal (SES-DF) decidiu acatar a orientação e estava no aguardo de novas doses da Pfizer. Atualmente, o DF aplica a quarta dose apenas para a população imunossuprimida. A orientação do ministério prevê que essa aplicação seja feita quatro meses após a primeira de reforço, para idosos com mais de 80 anos.", "30/03/2022", "Latest news", distritoFederal, 1203, 702)]
noticia_espirito_santo = [Noticia(7, "ES chega a 14.334 mortes e 1.039.074 casos confirmados de Covid-19", "Na comparação com a última atualização do Painel Covid-19, foram registrados mais 1 morte e 507 novos casos da doença.", "../static/img/covid.png", "O Espírito Santo registrou, até esta quarta-feira (30), 14.334 mortes por Covid-19. O número de casos confirmados chegou a 1.039.074. O índice de letalidade da doença no estado é de 1,38%. Os dados foram divulgados na plataforma Painel Covid-19, do governo do estado. Na comparação com os dados divulgados na terça (29), foram registrados mais uma morte e 507 novos casos da doença. As novas confirmações não significam, necessariamente, que os casos aconteceram de um dia para o outro, mas que foram contabilizadas no sistema neste período.", "30/03/2022", "Latest news", espiritoSanto, 1520, 802)]
noticia_goias = [Noticia(8, "Goiás tem 26.221 mortos e 1.273.979 casos de Covid-19", "A Secretaria da Saúde de Goiás (SES-GO) informa que há 1.273.979 casos de coronavírus 2019 (Covid-19) no território goiano. No Estado, há 770.051 casos suspeitos em investigação e 317.187 casos já foram descartados.", "../static/img/noticia1goias.jpg", "Há 26.221 óbitos confirmados de Covid-19 em Goiás até o momento, o que significa uma taxa de letalidade de 2,06%. Há 352 óbitos suspeitos que estão em investigação. Doses aplicadas: Levantamento realizado pela SES-GO apurou que, referente à primeira dose, foram aplicadas  5.668.843  doses das vacinas contra a Covid-19 em todo o Estado. Em relação à segunda dose e a dose única, foram vacinadas 4.916.906 pessoas, e 1.776.812 pessoas já receberam a dose de reforço.  Entre as crianças de 5 a 11 anos, 37,90% já receberam uma dose da vacina. Esses dados são preliminares e coletados junto ao Sistema de Informações do Programa Nacional de Imunizações (SI-PNI), do Ministério da Saúde.", "29/03/2022", "Latest news", goias, 6032, 320)]
noticia_maranhao = [Noticia(9, "Em uma semana, Maranhão registra mais de 2 mil casos de Covid-19", "Os registros são de 21 a 28 de março e foram obtidos a partir do boletim epidemiológico divulgado pela Secretaria de Estado da Saúde (SES).", "../static/img/noticia1maranhao.jpg", "Em uma semana, o Maranhão registrou 2.428 casos e 12 mortes por Covid-19, segundo dados da Secretaria de Estado da Saúde (SES). Os registros são de 21 a 28 de março e foram obtidos a partir do boletim epidemiológico que é divulgado diariamente pela pasta. Nesta segunda-feira (28), foram registrados 224 novos casos da doença e uma morte na cidade de Sítio Novo. Destes, 5 aconteceram na Grande Ilha de São Luís, 17 em Imperatriz e 202 em outras regiões do estado. Segundo a secretaria, o número de casos ativos (pessoas que, no momento, estão com Covid-19) caiu e chegou a 3.210 nesta segunda-feira (28). Desses, 3.150 pacientes foram orientados a ficar em isolamento domiciliar, 32 estão internados em enfermarias e 28 estão em Unidades de Terapia Intensiva (UTI).", "28/03/2022", "Latest news", maranhao, 6274, 789)]
noticia_mato_grosso = [Noticia(10, "Terça-feira (29): Mato Grosso registra 725.625 casos e 14.864 óbitos por Covid-19", "Há 59 internações em UTIs públicas e 37 em enfermarias públicas; taxa de ocupação está em 24% para UTIs e em 8% para enfermaria", "../static/img/noticia1matogrosso.jpg", "A Secretaria de Estado de Saúde (SES-MT) notificou, até a tarde desta terça-feira (29.03), 725.625 casos confirmados da Covid-19 em Mato Grosso, sendo registrados 14.864 óbitos em decorrência do coronavírus no Estado. Foram notificadas 513 novas confirmações de casos de coronavírus no Estado. Dos 725.625 casos confirmados da Covid-19 em Mato Grosso, 578 estão em isolamento domiciliar e 709.605 estão recuperados. Entre casos confirmados, suspeitos e descartados para a Covid-19, há 59 internações em UTIs públicas e 37 em enfermarias públicas. Isto é, a taxa de ocupação está em 24,39% para UTIs adulto e em 8% para enfermaria adulta. Dentre os dez municípios com maior número de casos de Covid-19 estão: Cuiabá (129.374), Várzea Grande (52.493), Rondonópolis (44.214), Sinop (33.651), Tangará da Serra (23.122), Lucas do Rio Verde (22.625), Sorriso (22.306), Primavera do Leste (21.762), Cáceres (16.772) e Alta Floresta (14.010).", "29/03/2022", "Latest news", matoGrosso, 3025, 122)]
noticia_mato_grosso_sul = [Noticia(11, "SES confirma 210 casos novos e 3 óbitos por Covid no Estado de Mato Grosso do Sul", "A Secretaria de Estado de Saúde (SES) registrou 210 novos casos de Covid em Mato Grosso do Sul nesta quinta-feira (31)", "../static/img/noticia1matogrossosul.jpg", "A Secretaria de Estado de Saúde (SES) registrou 210 novos casos de Covid em Mato Grosso do Sul nesta quinta-feira (31). As novas infecções foram confirmadas em diversos municípios do Estado, entre eles Campo Grande (58), Rio Verde de Mato Grosso (22), Paranaíba (20), Itaporã (18) e Juti (14). A média móvel de casos está em 271. O boletim epidemiológico Covid também registrou 3 óbitos ocorridos entre os dias 03 a 30 de março no  Estado, sendo dois em Campo Grande e um em Caarapó. Atualizada a média móvel da última semana no Estado está em 3,3. Mato Grosso do Sul conta com 2.491 casos ativos, sendo 2.449 em isolamento domiciliar e outros 42 hospitalizados. Os casos internados ocupam 15 leitos clínicos e 27 leitos de UTI. A taxa global de ocupação de leitos SUS/UTI adulto no Estado conta com 72% em Campo Grande, 57% em Dourados, 53% em Corumbá e 22% em Três Lagoas.", "31/03/2022", "Latest news", matoGrossoSul, 2449, 240)]
noticia_minas_gerais = [Noticia(12, "Mais um estudo deixa evidente ineficácia da ivermectina no tratamento da Covid-19", "Pessoas que tomaram medicamento após diagnóstico da doença tiveram quadro pior do que os que não tomaram", "../static/img/noticia1minasgerais.png", "A ivermectina não se mostrou eficaz para evitar que pacientes com Covid-19 fossem internados, de acordo com o resultado de um grande ensaio clínico publicado na quarta-feira (30). A pesquisa envolveu 1.358 pessoas infectadas pelo novo coronavírus de 12 cidades de Minas Gerais. Os resultados foram publicados no The New England Journal of Medicine. Pesquisadores realizaram um estudo duplo-cego, com pacientes que tiveram sintomas de Covid-19 por até sete dias entre 23 de março de 2021 e 6 de agosto de 2021, principal pico de mortes da pandemia no Brasil. Metade foi aleatoriamente designada para ser medicada com ivermectina (679 pacientes) e a outra metade recebeu placebo (679 pacientes). 'O resultado demonstrou que nós não tivemos nenhuma sinalização de benefício da medicação para tratar a Covid', diz em entrevista ao Estadão o pesquisador e professor da Pontifícia Universidade Católica de Minas Gerais (PUC-Minas) Gilmar Reis, que liderou o estudo. Voluntários que tomaram ivermectina nos primeiros três dias após um teste positivo de Covid-19, inclusive, tiveram resultados piores do que os do grupo placebo. O estudo foi revisado por pares antes de ser publicado no periódico científico. A ivermectina normalmente é usada como medicamento antiparasitário e demonstrou ter eficácia clínica no tratamento contra oncocercose (infecção por verme), estrongiloidíase (infecção intestinal) e sarna. No início da pandemia, pesquisadores passaram a testar vários medicamentos contra a Covid-19 e surgiu a hipótese de que a ivermectina poderia bloquear o coronavírus, o que não se confirmou.", "31/03/2022", "Latest news", minasGerais, 19697, 7330)]
noticia_para = [Noticia(13, "Pará registra 753.977 casos e 18.092 mortes por Covid-19", "Secretaria de Saúde confirmou mais 714 casos de Covid-19 e 3 mortes.", "../static/img/noticia1para.jpg", "O Pará contabilizou mais 714 casos de Covid-19 e 3 mortes causadas pela doença, segundo o boletim divulgado pela Secretaria de Saúde Pública do Pará (Sespa) nesta quarta-feira (30). Agora são 753.977 pessoas diagnosticadas com a doença desde março de 2020, sendo que 18.092 morreram. Houve 7 novos casos confirmados e nenhuma morte registradas nos últimos sete dias. Em relação à subnotificação das prefeituras, foram confirmados mais 707 casos e 3 mortes ocorridas em dias anteriores. O Pará possui, até então, 713.760 recuperados, 157.278 descartados e 30 casos em análise.", "30/03/2022", "Latest news", para, 7581, 510)]
noticia_paraiba = [Noticia(14, "Paraíba faz Dia D de vacinação contra Covid-19 nesta sexta (1º) e no sábado (2)", "De acordo com o secretário Geraldo Medeiros, cerca de 1,5 milhão de paraibanos não recebeu dose de reforço", "../static/img/noticia1paraiba.jpg", "O secretário estadual de Saúde, Geraldo Medeiros, reforçou a necessidade de realizar mais um dia de mobilização para que a população possa se apresentar nos postos de vacinação. 'Ainda há cerca de 1,5 milhão de pessoas que não receberam a dose de reforço em tempo oportuno e a Paraíba ainda não atingiu a meta de 90% da população vacinável com duas doses ou dose única da vacina contra a Covid-19', alertou. Geraldo Medeiros destaca que o objetivo da ação é facilitar o acesso da população paraibana que, por diversos motivos não conseguiu concluir o esquema vacinal contra Covid-19. “Estamos em um momento de redução nos números de casos e óbitos e podemos tornar isso uma constante com o avanço da vacinação e as medidas de proteção individuais”, destacou o secretário.", "01/04/2022", "Latest news", paraiba, 3766, 528)]
noticia_parana = [Noticia(15, "Paraná confirma 2.534 casos de Covid-19 e 15 óbitos", "A Sesa (Secretaria de Estado da Saúde) divulgou, nesta quinta-feira (31), mais 2.534 casos confirmados de Covid-19 e 15 óbitos em decorrência da doença. Os números são de meses e semanas anteriores, portanto, não representam necessariamente as notificações das últimas 24 horas.", "../static/img/noticia1parana.jpg", "A Sesa (Secretaria de Estado da Saúde) divulgou, nesta quinta-feira (31), mais 2.534 casos confirmados de Covid-19 e 15 óbitos em decorrência da doença. Os números são de meses e semanas anteriores, portanto, não representam necessariamente as notificações das últimas 24 horas. Os casos confirmados são de março (1.245), fevereiro (658) e janeiro (590) de 2022; dezembro (2), outubro (2), setembro (4), agosto (1), julho (3), junho (2), maio (1), abril (3), março (4), fevereiro (4) e janeiro (2) de 2021; e dezembro (9), outubro (1), setembro (2) e julho (1) de 2020. Os óbitos são de março (12) e fevereiro (2) de 2022 e abril (1) de 2021. As vítimas são sete mulheres e oito homens, com idades entre oito e 93 anos. Elas residiam em Ponta Grossa (2), Londrina (2), Cascavel (2), Terra Boa, Piraí do Sul, Marechal Cândido Rondon, Jaguariaíva, Ivaiporã, Irati, Cornélio Procópio, Campo Largo e Bom Jesus do Sul.", "31/03/2022", "Latest news", parana, 10444, 2526)]
noticia_pernambuco = [Noticia(16, "PE decreta emergência em saúde e encerra calamidade pública; estado tem 896,2 mil casos e 21,4 mil mortes por Covid", "De acordo com o estado, isso significa que o governo entendeu a melhoria da crise sanitária e que não deveria mais prorrogar o estado de calamidade pública, em vigor desde o início da pandemia.", "../static/img/noticia1pernambuco.jpeg", "Pernambuco atingiu a marca de 896.215 casos confirmados do novo coronavírus. Desde março de 2020, o estado acumulou 21.400 mortes. Nesta quarta (30), diante da redução dos registros, o governo decretou estado de emergência em saúde pública. Isso significa uma situação menos grave do que o estado de calamidade pública, em vigor desde o início da pandemia. Ainda de acordo com o estado, a Nota Técnica nº 12/2022, da Secretaria Estadual de Saúde, “reconhece que o cenário presente da Covid-19 em Pernambuco não justifica a renovação do atual estado de calamidade pública, em vigor até 31 de março de 2022”. No entanto, esse documento recomenda a decretação do “estado de emergência em saúde pública”, a fim de permitir, “sem solução de continuidade”, a transição segura para a “situação de normalidade”. O estado também determina a “permanência dos mecanismos de vigilância e resposta necessários à gestão operacional e estratégica das ações de combate à pandemia.” Publicado no Diário Oficial desta quarta, o decreto Nº 52.505, de 29 de março, informa que o estado de emergência em saúde pública foi declarado por causa “da emergência de saúde pública de importância internacional decorrente do coronavírus, desastre de natureza biológica, causado por epidemia de doenças infecciosas virais.”", "30/03/2022", "Latest news", pernambuco, 8796, 2643)]
noticia_piaui = [Noticia(17, "Mulher de 84 anos e jovem de 23 anos morrem vítimas da Covid-19 no Piauí", "O estado registrou 23 novos infectados pela doença nas últimas 24 horas e soma 367.670 casos confirmados.", "../static/img/noticia1piaui.jpg", "O Piauí registrou 23 casos confirmados e dois óbitos por Covid-19, nas últimas 24 horas, segundo dados divulgados pela Secretaria de Estado da Saúde, nesta quarta-feira (30). Dos 23 casos confirmados 16 são de mulheres e 7 de homens, com idades que variam de 03 a 62 anos. Uma mulher de Altos (84 anos) e um homem de Novo Santo Antônio (23 anos) não resistiram às complicações da Covid-19. Os casos confirmados no estado somam 367.670 em todos os municípios piauienses. Já os óbitos pelo novo coronavírus chegam 7.728 casos e foram registrados em 224 municípios. Dos leitos existentes na rede de saúde do Piauí para atendimento à Covid-19, 94 estão ocupados, sendo 60 leitos clínicos, 31 UTI’s e 03 leitos de estabilização. As altas acumuladas somam 25.989 até o dia 30 de março de 2022. A Sesapi estima que 359.848 pessoas já estão recuperadas ou seguem em acompanhamento (casos registradas nos últimos 14 dias) que não necessitaram de internação ou evoluíram para morte.", "30/03/2022", "Latest news", piaui, 3118, 1002)]
noticia_rio_janeiro = [Noticia(18, "Rio reduz intervalo da Pfizer para crianças", "A partir de hoje (31), o intervalo entre a primeira e a segunda dose da vacina Pfizer pediátrica passa a ser de 21 dias.", "../static/img/noticia1riodejaneiro.jpg", "A partir de hoje, 31/03, o intervalo entre a primeira e a segunda dose da vacina Pfizer pediátrica passa a ser de 21 dias. Ou seja, crianças que tomaram a primeiro dose dose deste imunizante há 21 dias ou mais podem ir aos postos a partir de hoje para completar o esquema vacinal com a segunda dose.", "31/03/2022", "Hottest news", rioJaneiro, 15989, 9157)]
noticia_rio_grande_norte = [Noticia(19, "Taxa de ocupação de leitos de UTI para Covid-19 fica abaixo de 10% no RN", "Ocupação é a menor registrada na série histórica do Regula RN.", "../static/img/noticia1riograndenorte.jpg", "O Rio Grande do Norte registrou taxa de ocupação dos leitos críticos de Covid-19 abaixo de 10% nesta terça-feira (22). Os dados são do sistema Regula RN, usado para administração dos leitos na rede pública no estado. Até a noite da terça, a taxa era de 9,45% - apenas 12 pessoas estavam internadas com a doença. Essa é a menor taxa registrada desde o início da pandemia, de acordo com a série história disponibilizada pelo sistema. Outros 19 leitos de UTI Covid-19 eram ocupados por pessoas sem a doença, por volta das 19h50. Segundo o governo, esses pacientes não são contabilizados para a taxa. A região Oeste tinha uma ocupação de apenas 4,2%. Já o maior percentual no estado era o da região Seridó, que tinha 13,3% de ocupação. Segundo a Secretaria Estadual de Saúde, 460 novos casos da Covid-19 foram registrados no estado em 24 horas entre a segunda-feira (21) e esta terça-feira (22). Apesar disso, o estado chegou ao sexto dia sem registrar nenhuma morte por Covid-19. O estado contabiliza 493.375 casos confirmados da doença e 8.116 mortes desde março de 2020.", "22/03/2022", "Latest news", rioGrandeNorte, 3168, 998)]
noticia_rio_grande_sul = [Noticia(20, "Ocupação de UTIs por Covid-19 é a menor em 85 dias no RS", "Estado tem 146 pacientes diagnosticados com a doença em estado grave", "../static/img/noticia1riograndesul.jpg", "O Rio Grande do Sul voltou a registrar queda da ocupação das Unidades de Terapia Intensiva (UTIs), com 146 pacientes diagnosticados com a doença em estado grave nesta quinta-feira. É o menor número de internações por conta do novo coronavírus em leitos de UTI desde 4 de janeiro deste ano, quando havia 146 pacientes com a doença. De acordo com Painel Coronavírus, da Secretaria Estadual da Saúde (SES), são 87 casos a menos em relação a 14 dias atrás, quando havia 233 pacientes com Covid-19, e uma redução de 37% no período. Com um total de 1.754 pacientes em UTIs - que envolve internações por todas as doenças - a ocupação geral era de 67,4% dos 2.602 leitos disponíveis. Em um mês, houve redução de 472 leitos de UTI no Estado, que no início de março contava com 3.074 unidades. O boletim epidemiológico divulgado pela SES nesta quinta informou mais 13 óbitos em decorrência de complicações da Covid-19, elevando o total de mortes no Estado para 39.049 desde o início da pandemia. Segundo a SES, 3.648 novos casos da doença foram confirmados, totalizando 2.274.550.", "31/03/2022", "Latest news", rioGrandeSul, 10693,3975)]
noticia_rondonia = [Noticia(21, "Dia estadual de homenagem às vítimas da Covid-19: Rondônia já perdeu mais de 7 mil pessoas para a doença", "Lei estadual estabeleceu 29 de março como dia em memória às vítimas da pandemia em Rondônia. Confira histórias — para além dos números.", "../static/img/noticia1rondonia.jpg", "Há exatamente dois anos, familiares, amigos e a população de Rondônia lamentavam a primeira morte por Covid-19 no estado. Esta terça-feira (29) é marcada pelo dia estadual em homenagem às 7.175 vidas perdidas pela doença desde o início da pandemia. Uma das vítimas foi Maryluce Ferreira. Ela faleceu aos 38 anos, em 10 de maio de 2020, Dia das Mães. Segundo o irmão, Thiago Gonçalves, ela era funcionária pública, se doava pela cultura rondoniense e sempre tinha um sorriso no rosto 'de orelha a orelha'. 'Era dia das mães, mas hoje eu não tenho mais a minha mãe, a minha mãe-avó e nem a minha irmã', comenta entre lágrimas. A dor de Thiago é de saudade, mas também de lembrar da forma como a irmã se foi. Rapidamente e sem oportunidade de despedida. 'Eu saí da UPA [Unidade de Pronto Atendimento] pra ir lá pro Cemetron [Centro de Medicina Tropical de Rondônia], a última imagem que eu tenho dela é ela se batendo na maca, pra entrar na ambulância. Até hoje está na minha mente', relembra.", "29/03/2022", "Latest news", rondonia, 1562, 482)]
noticia_roraima = [Noticia(22, "Cáritas em Roraima distribui kit de higiene pessoal e de prevenção à Covid para migrantes recém-chegados da Venezuela", "Mais de 550 kits foram distribuídos, nessa quarta-feira (30), para a população abrigada no Posto de Recepção e Apoio, em Boa Vista.", "../static/img/noticia1roraima.jpg", "A Cáritas Brasileira iniciou a distribuição distribuição de kits de higiene pessoal e de prevenção à Covid-19 para migrantes recém-chegados da Venezuela em Boa Vista. Até essa quinta-feira (31) foram entregues 554 itens. A ação integra o projeto Orinoco: Águas que Atravessam Fronteiras. A distribuição iniciou na última terça-feira (29) e marca o início do novo ciclo de entrega de kits do Orinoco, que ocorre por etapas, a fim de garantir que a população migrante e refugiada esteja assistida continuamente. No total, serão entregues 1,5 mil kits, no período de seis meses. Os kits individuais de higiene pessoal e de prevenção à Covid-19 contêm produtos que atendem as necessidades básicas de homens, mulheres e crianças: sabão em pó, álcool gel, máscara de tecido, creme dental, escova de dentes, sabonetes, xampu e condicionador, pente de cabelo, desodorante. Além de fraldas, lenços umedecidos, toalha, dentre outros produtos de cuidados pessoais. Além da entrega dos produtos, ocorreram rodas de promoção de higiene, reforçando os momentos mais importantes da lavagem de mãos e o reforço sobre o uso de máscara, no contexto de prevenção a pandemia do coronavírus. O trabalho iniciou no Posto de Recepção e Apoio (PRA), ao lado da rodoviária, em Boa Vista. “Distribuímos 365 kits no período da manhã e tarde para migrantes recém-chegados da Venezuela, e 190 kits no período da noite, para a população em situação de rua que pernoita no PRA. Foram atendidos homens, mulheres e crianças que receberam o kit de higiene pessoal e também de prevenção à Covid”, explicou Aline Coelho Nogueira, assessora local de monitoramento do Orinoco em Roraima. Orinoco é da rede Cáritas e recebe o apoio do escritório de População, Refúgio e Migração (PRM) dos Estados Unidos.", "01/04/2022", "Latest news", roraima, 450, 190)]
noticia_santa_catarina = [Noticia(23, "SC anuncia fim do estado de calamidade pública por causa da Covid; saiba o que muda", "Decreto acaba nesta quinta-feira (31) e não será renovado. Com a decisão, o Centro de Operações em Emergências em Saúde (COES) deixa de existir.", "../static/img/noticia1santacatarina.jpg", "O governador de Santa Catarina, Carlos Moisés (Republicanos), confirmou nesta quinta-feira (31) que não irá prorrogar o estado de calamidade pública por conta da pandemia de Covid-19 no estado. O decreto tem validade até as 23h59 de hoje. Com a nova decisão, o Centro de Operações em Emergências em Saúde (COES) deixa de existir. Criado no início da pandemia, o órgão foi responsável para dar suporte nas decisões tomadas pelos prefeitos e secretários no enfrentamento contra o avanço da doença. A Secretaria de Estado da Saúde informou, porém, que o mapa de risco da Covid divulgado semanalmente e os boletins diários, com os números de casos, mortes e ocupação de leitos de Unidade de Terapia Intensiva (UTI), vão continuar. Publicado pela primeira vez em 17 de abril de 2020, o decreto 562/2020 possibilitou que o estado implementasse o mapa de risco sanitário que avalia semanalmente a situação da doença no estado, tomou decisões sobre obrigatoriedade da máscara, isolamento social e proibição de eventos, por exemplo. A decisão também permitiu aos municípios criarem regramentos mais rígidos no combate ao vírus, de acordo com a realidade de cada região.", "31/03/2022", "Latest news", santaCatarina, 6248, 3601)]
noticia_sao_paulo = [Noticia(24, "Estado de SP tem queda de 87% no número de internações por Covid-19 em relação ao pico da ômicron", "Desde 16 de março, estado registra, diariamente, a menor média móvel de novas internações por Covid-19 desde o início da pandemia. No pico da ômicron, em 29 de janeiro deste ano, índice chegou a ser de 1.521 hospitalizações diárias.", "../static/img/noticia1saopaulo.jpg", "O estado de São Paulo registrou uma queda de 87% na média móvel de novas internações por Covid-19 em relação ao pior momento da variante ômicron neste ano. Nesta terça-feira (29), em média, 189 hospitalizações provocadas pela doença. No pico da ômicron, em 29 de janeiro deste ano, essa média chegou a ser de 1.521 internações diárias. Os dados consideram internações em leitos de enfermaria e de Unidade de Terapia Intensiva (UTI), em hospitais particulares e públicos, de pacientes com confirmação ou suspeita de Covid-19. A média móvel leva em consideração os dados dos últimos sete dias. A queda foi comemorada pelo governo de São Paulo em coletiva de imprensa nesta quarta-feira (30). 'Com a queda crescente de pacientes com coronavírus, os hospitais estaduais abrem agora mais leitos para atendimento às pessoas com outras doenças', disse o governador João Doria (PSDB). Desde 16 de março, o estado está batendo, sucessivamente, o recorde de menor média móvel de internações por Covid-19. Antes disso, o menor número havia sido registrado no ano passado, em 10 de dezembro, com 269 hospitalizações. No pior momento da pandemia, em 26 de março de 2021, o índice chegou a ser de 3.399 novas internações diárias. Na época, o estado enfrentou esgotamento de leitos e ao menos 230 pessoas com Covid-19 ou suspeita morreram na fila por um leito de UTI na região metropolitana.", "30/03/2022", "Hottest news", saoPaulo, 41262, 13290)]
noticia_sergipe = [Noticia(25, "Sergipe registra 143 novos casos conhecidos de Covid-19 e duas mortes", "Desde o início da pandemia, 325.921 pessoas testaram positivo para a doença e 6.317 morreram.", "../static/img/noticia1sergipe.jpg", "Nesta quinta-feira (31), Sergipe registrou 143 novos casos conhecidos de Covid-19 e duas mortes. A informação foi divulgada pela Secretaria da Saúde de Sergipe (SES). Os dois óbitos confirmados foram: um homem, 78 anos, de Porto da Folha, com hipertensão e ex-tabagista; um homem, 76 anos, de Aracaju, com hipertensão, diabetes e coronariopatia. A taxa de letalidade é de 1,9%, a de mortalidade 274,8 e a de incidência 14.178,5. ", "31/03/2022", "Latest news", sergipe, 2068, 890)]
noticia_tocantis = [Noticia(26, "Tocantins tem mais de 100 novos casos de Covid e uma morte pela doença", "Desde o início da pandemia o estado soma 302.826 diagnósticos e 4.144 óbitos.", "../static/img/noticia1tocantis.jpg", "O Tocantins contabilizou 103 novos casos de Covid-19 nesta quinta-feira (31), sendo que 32 foram diagnosticados nas últimas 24 horas. Conforme a Secretaria Estadual de Saúde (SES), uma morte pela doença foi registada. Desde o início da pandemia o estado soma 302.826 diagnósticos e 4.144 óbitos. A morte aconteceu em 26 de fevereiro, mas só foi confirmada neste boletim. A paciente que não resistiu é uma idosa de 87 anos que morava em Araguaína. Ela tinha diabetes e hipertensão. O óbito foi registrado no Hospital Regional de Araguaína.", "31/03/2022", "Latest news", tocantis, 1383, 766)]

acre.set_noticia_lista(noticia_acre)
alagoas.set_noticia_lista(noticia_alagoas)
amapa.set_noticia_lista(noticia_amapa)
amazonas.set_noticia_lista(noticia_amazonas)
bahia.set_noticia_lista(noticia_bahia)
ceara.set_noticia_lista(noticia_ceara)
distritoFederal.set_noticia_lista(noticia_distrito_federal)
espiritoSanto.set_noticia_lista(noticia_espirito_santo)
goias.set_noticia_lista(noticia_goias)
maranhao.set_noticia_lista(noticia_maranhao)
matoGrosso.set_noticia_lista(noticia_mato_grosso)
matoGrossoSul.set_noticia_lista(noticia_mato_grosso_sul)
minasGerais.set_noticia_lista(noticia_minas_gerais)
para.set_noticia_lista(noticia_para)
paraiba.set_noticia_lista(noticia_paraiba)
parana.set_noticia_lista(noticia_parana)
pernambuco.set_noticia_lista(noticia_pernambuco)
piaui.set_noticia_lista(noticia_piaui)
rioJaneiro.set_noticia_lista(noticia_rio_janeiro)
rioGrandeNorte.set_noticia_lista(noticia_rio_grande_norte)
rioGrandeSul.set_noticia_lista(noticia_rio_grande_sul)
rondonia.set_noticia_lista(noticia_rondonia)
roraima.set_noticia_lista(noticia_roraima)
santaCatarina.set_noticia_lista(noticia_santa_catarina)
saoPaulo.set_noticia_lista(noticia_sao_paulo)
sergipe.set_noticia_lista(noticia_sergipe)
tocantis.set_noticia_lista(noticia_tocantis)

lista_noticias = [noticia_acre, noticia_alagoas, noticia_amapa, noticia_amazonas, noticia_bahia, noticia_ceara, noticia_distrito_federal, noticia_espirito_santo, noticia_goias, noticia_maranhao,noticia_mato_grosso, noticia_mato_grosso_sul, noticia_minas_gerais, noticia_para, noticia_paraiba, noticia_parana, noticia_pernambuco, noticia_piaui, noticia_rio_janeiro, noticia_rio_grande_norte, noticia_rio_grande_sul, noticia_rondonia, noticia_roraima, noticia_santa_catarina, noticia_sao_paulo, noticia_sergipe, noticia_tocantis]

lista_estados = [acre, alagoas, amapa, amazonas, bahia, ceara, distritoFederal, espiritoSanto, goias, maranhao, matoGrosso, matoGrossoSul, minasGerais, para, paraiba, parana, pernambuco, piaui, rioJaneiro, rioGrandeNorte, rioGrandeSul, rondonia, roraima, santaCatarina, saoPaulo, sergipe, tocantis]


@app.route("/")
def home():
    return render_template ("index.html", noticias=lista_noticias, estados=lista_estados)

@app.route("/noticia/<int:id>")
def exibir_noticia(id):
    for noticia in lista_noticias:
        if noticia[0].get_id() == int(id):
            return render_template("noticia.html", noticia=lista_noticias[int(id)], estados=lista_estados)
    return render_template ("index.html", noticias=lista_noticias)

@app.route("/estado/<string:sigla>")
def noticias_do_estado(sigla):
    for estado in lista_estados:
        if estado.get_sigla() == sigla:
            return render_template("estado.html", noticias=estado.get_noticia_lista(), estados=lista_estados)
    return render_template("index.html", estados=lista_estados)
